### ISSUE TITLE
io file error

### ISSUE THREAD

**Issue by zachcp** [substance/io#5]
Hi Team Substance,

I am looking forward to using IO but run into errors following installation. I installed as per the IO instructions, got some errors and am able to replicate the error following install of the cutting edge version. I'm on Mac using `npm` from Homebrew.

```
npm install -g substance-io@0.0.0
git clone https://github.com/substance/docs.git
io docs/blog  

Core module "fs" has not yet been ported to the browser
Substance.io running on port 5000
http://127.0.0.1:5000/

#interact with webpage
serving resource /src/substance.js
serving resource /node_modules/substance-surface/index.js
serving resource /node_modules/substance-surface/src/surface.js
serving resource /node_modules/substance-commander/index.js
...
...
...
serving resource /node_modules/substance-library/src/library_controller.js
serving resource /node_modules/substance-library/src/collection.js
serving resource /src/substance_view.js
Error: ENOTDIR, not a directory 'docs/blog/content_is_data/content.md/index.json'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at /usr/local/lib/node_modules/substance-io/src/io.js:65:32
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/local/lib/node_modules/substance-io/node_modules/underscore/underscore.js:79:11)
    at /usr/local/lib/node_modules/substance-io/src/io.js:61:7
    at Array.forEach (native)
    at Function._.each._.forEach (/usr/local/lib/node_modules/substance-io/node_modules/underscore/underscore.js:79:11)
    at Function.IO.extractLibrary (/usr/local/lib/node_modules/substance-io/src/io.js:39:5)
    at /usr/local/lib/node_modules/substance-io/server.js:100:20
```

**Comment by obuchtala** [comment]
Hi,

thank you.
As we tried to show some cutting edge features we obviously have broken 
something.
Sorry for that.
We will fix it asap (= tomorrow after a nice sleep ;) )

Cheers,
Oliver

Am 24.10.2013 21:01, schrieb zachcp:

**Comment by michael** [comment]
Maybe use the git version for now, until we packaged a stable 0.2.0 build for npm.

https://github.com/substance/io#development-environment

Let me know if you are having troubles.
